### ISSUE TITLE
Config and Country have same shorthand

### ISSUE THREAD

**Issue by atharva29** [falcosecurity/falcoctl#114]
**What happened**:
When I tried to generate generate certificates it gave me following error
My command was: `FALCOCTL_NAME=falco-grpc.default.svc.cluster.local FALCOCTL_PATH=/tmp/certs ./falcoctl install tls`
`
```
panic: unable to redefine 'c' shorthand in "tls" flagset: it's already used for "country" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000164f00, 0xc0002f70e0)
        /home/atharva/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x3f5
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc0002f70e0)
        /home/atharva/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:887 +0x65
github.com/spf13/pflag.(*FlagSet).VisitAll(0x3, 0xc00029fcd8)
        /home/atharva/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0xe3
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc000308000, 0x0)
        /home/atharva/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:885 +0x3d
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc000308000)
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1612 +0x65
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0xc0002c3610)
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1004 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000308000, {0xbd6df8, 0x0, 0x0})
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:766 +0x107
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c7080)
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/atharva/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:880
github.com/falcosecurity/falcoctl/cmd.Execute()
        /home/atharva/apps/falcoctl/cmd/root.go:89 +0x76
main.main()
        /home/atharva/apps/falcoctl/main.go:23 +0x17
```
**What you expected to happen**:
- As `country` and `config` have same shorthand due to which error caused. Ideally it should generate certs

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I will attach PR to this

**Comment by leogr** [comment]
Fixed by #115 
Thank you!

/close
